name: Push to main directory

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    
  
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: './'
          destination-github-username: 'Maison-Hochard'
          destination-repository-name: 'helpr'
          target-directory: 'app'
          user-email: hugo.richard@epitech.eu
          target-branch: master
